INSERT INTO vitacorpus.TBL_RUTINA (rutina, CAT_OBJETIVO_idObjetivos) VALUES
("Semana 1: Activación inicial para bajar grasa", 1),
("Semana 2: Aumento de volumen para bajar grasa", 1),
("Semana 3: HIIT avanzado para bajar grasa", 1),
("Semana 4: Rutina avanzada para bajar grasa", 1),
("Semana 1: Rutina de fuerza básica para subir músculo", 2),
("Semana 2: Rutina intermedia de musculación", 2),
("Semana 3: Rutina avanzada de musculación", 2),
("Semana 4: Rutina de hipertrofia para subir músculo", 2),
("Semana 1: Rutina básica para definición corporal", 3),
("Semana 2: Rutina intermedia para definición corporal", 3),
("Semana 3: Rutina avanzada para definición corporal", 3),
("Semana 4: Rutina avanzada de tonificación para definición corporal", 3),
("Semana 1: Rutina básica para aumento de resistencia", 4),
("Semana 2: Rutina intermedia para aumento de resistencia", 4),
("Semana 3: Rutina avanzada para aumento de resistencia", 4),
("Semana 4: Rutina avanzada para resistencia", 4),
("Semana 1: Rutina ligera para ejercicio por salud", 5),
("Semana 2: Rutina de bajo impacto para ejercicio por salud", 5),
("Semana 3: Rutina para mejorar postura y elasticidad", 5),
("Semana 4: Rutina de tonificación para mantener un peso saludable", 5);
# ---------------------------------
# Inserción a la relación rutinas-ejercicios
# ---------------------------------
INSERT INTO vitacorpus.REL_RUTINA_EJ (TBL_RUTINA_idRutina, TBL_EJERCICIO_idEjercicio) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20);
