USE vitacorpus;

INSERT INTO vitacorpus.CAT_OBJETIVO VALUES
(1, "Bajar grasa"),
(2, "Subir masa muscular"),
(3, "Definición corporal"),
(4, "Mejorar resistencia"),
(5, "Ejercicio por salud");

INSERT INTO vitacorpus.CAT_ALIMENTOS_RESTRINGIDOS (alimento, sustituto1, sustituto2) VALUES
('Avena', 'Harina de avena', 'Copos de arroz'),
('Plátano', 'Manzana', 'Pera'),
('Nueces', 'Almendras', 'Pistachos'),
('Leche vegetal', 'Leche de almendra', 'Leche de coco'),
('Arroz integral', 'Quinoa', 'Arroz basmati integral'),
('Pollo', 'Pechuga de pavo', 'Tofu'),
('Brócoli', 'Espinacas', 'Col rizada'),
('Sopa de zanahoria', 'Sopa de calabaza', 'Sopa de tomate'),
('Lentejas', 'Garbanzos', 'Frijoles negros'),
('Rodajas de pepino', 'Zanahoria rallada', 'Apio'),
('Tomate', 'Pimiento rojo', 'Pepino'),
('Ensalada de atún', 'Ensalada de garbanzos', 'Ensalada de tofu'),
('Arroz basmati', 'Arroz integral', 'Quinoa'),
('Yogur vegetal', 'Yogur de soja', 'Yogur de coco'),
('Hamburguesa de pollo', 'Hamburguesa de lentejas', 'Hamburguesa de soya'),
('Tostadas integrales', 'Pan de centeno', 'Pan sin gluten'),
('Aguacate', 'Hummus', 'Pesto de albahaca'),
('Frutos secos', 'Semillas de girasol', 'Semillas de calabaza'),
('Quinoa', 'Arroz integral', 'Cuscús integral'),
('Pescado', 'Tofu', 'Seitán'),
('Zanahorias', 'Apio', 'Pepino'),
('Setas', 'Champiñones', 'Tofu'),
('Manzana', 'Pera', 'Uvas'),
('Espinacas', 'Acelga', 'Lechuga'),
('Garbanzos', 'Lentejas', 'Frijoles negros'),
('Tempeh', 'Tofu', 'Seitán'),
('Huevo', 'Tofu revuelto', 'Aquafaba'),
('Crema de cacahuate', 'Crema de almendra', 'Mantequilla de maní'),
('Pimiento', 'Tomate', 'Cebolla'),
('Aceite de oliva', 'Aceite de coco', 'Aceite de aguacate');